name: ci 
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/karpovilia/test-gp-docker-action/my-cool-service-ki:latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      # - name: Assemble joint bibliography
        # run: | 
          # cd service
          # jq -s 'add' *.json > bibliography.json
      
      - name: Compile
        run: |
          pandoc \
          --pdf-engine=xelatex \
          -V mainfont="CMU Serif" \
          -V monofont="CMU Typewriter Text" \
          --toc \
          --toc-depth=2 \
          --filter=pandoc-crossref \
          --csl=service/apa.csl \
          --bibliography=service/bibliography.json \
          --metadata-file=text/000_metadata.md \
          --number-sections \
          --citeproc \
          --output=output.pdf text/*.md
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Changed files
